### ISSUE TITLE
Reindent lines

### ISSUE THREAD

**Issue by vukanac** [colinta/ApacheConf.tmLanguage#16]
Is it possible to re-indent all lines?

I have a file that is not indented correctly:

    <VirtualHost *:80>
    <Directory "/var/www/html">
    # comment
            AllowOverride All
    Order Allow,Deny
        Allow from all
            Require all granted
    </Directory>
        # comment
    </VirtualHost>
    # comment

STEPS:

* Select all
* >Edit >Line >Reindent

Nothing is re-indent.
If XML highlight, re-indent is done correctly, but commenting is not correct!

EXPECTED:

    <VirtualHost *:80>
        <Directory "/var/www/html">
            # comment
            AllowOverride All
            Order Allow,Deny
            Allow from all
            Require all granted
        </Directory>
        # comment
    </VirtualHost>
    # comment

**Comment by colinta** [comment]
Hmm, I have no idea how to fix this :-/
