### ISSUE TITLE
A few commands not have highlighting

### ISSUE THREAD

**Issue by mrmlnc** [colinta/ApacheConf.tmLanguage#17]
_From @Nitrinax on September 10, 2016_

following syntax commands are not highlighted on windows

- ErrorLogFormat
- GlobalLog
- PHPIniDir
- SSLHonorCipherOrder
- SSLCompression
- SSLUseStapling
- SSLStapling*
- SSLCARevocationCheck
- SSLSRPVerifierFile
- SSLSessionTickets
- RequestReadTimeout
- ProxyHTML*
- MaxRanges

_Copied from original issue:_ https://github.com/mrmlnc/vscode-apache/issues/1

**Comment by colinta** [comment]
Added 6ca9249 to address these.

**Comment by colinta** [comment]
Available in v1.1.2

**Comment by mrmlnc** [comment]
@colinta, thanks you!
