### ISSUE TITLE
.htaccess Syntax Highlighting Not Working Without Config

### ISSUE THREAD

**Issue by rothkj1022** [colinta/ApacheConf.tmLanguage#18]
It should be noted that after installation, to see syntax highlighting in .htaccess files you need to go to View -> Syntax -> Open all with current extension as -> Apache Conf.

**Comment by colinta** [comment]
Yeah but that's the case with *all* syntax highlighting files.  I think it's up to the user to learn about Sublime Text's syntax highlighting configuration.

**Comment by rothkj1022** [comment]
Well, it wasn't obvious to me and I assumed the package didn't work at first.  I just thought adding a sentence to the Readme could help others.  Thank you for providing this plugin.

**Comment by colinta** [comment]
No you’re right it would be helpful - please make a pull request!
