### ISSUE TITLE
doesn't show up in package control

### ISSUE THREAD

**Issue by ckot** [colinta/ApacheConf.tmLanguage#8]
At least not on ST3 on OSX.  I was able to install using Package Control: Advanced Install Package by simply typing `ApacheConf.tmLanguage` though

**Comment by colinta** [comment]
Hmm, I'm also on ST3 on OSX.  I uninstalled and was able to find it:

![screen shot 2015-05-25 at 9 23 21 am](https://cloud.githubusercontent.com/assets/27570/7799138/c1d94f62-02bf-11e5-9a91-1037d3247b6d.png)

I don't want to close this until we know for sure what's going on, so let me know if you think this is still happening.

**Comment by ckot** [comment]
hmm.  my bad.  I must of had this package already installed but not enabled or something.  my bad.  I just uninstalled, and it got listed in package control, and I was able to install it.  Sorry for bugging you.

**Comment by colinta** [comment]
No worries! I'm glad you brought it up, I would want to know if something was wrong with it.
